### PR TITLE
Add optional return of cycles in `find_rainflow_ranges()`

### PR DESCRIPTION
**Pull request by adtzlr**
Hi @Gunnstein!

I went through your code and I tried to simplify the Example **Creating and plotting a rainflow matrix with fatpack and matplotlib.ipynb** by adding a `return_cycles` argument to the `find_rainflow_ranges()` function.

```python
S, Sm = fatpack.find_rainflow_ranges(y, return_means=True)
S, cycles = fatpack.find_rainflow_ranges(y, return_cycles=True)
S, Sm, cycles = fatpack.find_rainflow_ranges(y, return_means=True, return_cycles=True)
```

I also changed the notebook accordingly and added two tests.

- [x] Add `fatpack.find_rainflow_ranges(y, return_cycles=True)`
- [x] Simplify notebook example **Creating and plotting a rainflow matrix with fatpack and matplotlib.ipynb** https://github.com/Gunnstein/fatpack/pull/17/commits/9d2ae0476b2f113e73cc094d009bca37f3a06d58
- [x] Flip start/destination columns of the cycles for the second pass of the rainflow algorithm https://github.com/Gunnstein/fatpack/pull/17/commits/99fd00bd755e28fa69786bf706953d9609dad5b4 (this was not necessary before because only ranges and means were returned)
- [x] Add Tests

### Edit
It turns out that it is necessary to flip the start and destination columns of the cycles array for the second pass. Now

```python
fatpack.find_rainflow_ranges(np.array([0, 1, -1, 0]), return_cycles=True)
```

returns

```
(array([2.]), array([[ 1., -1.]]))
```

### CODE REVIEW

**Comment by adtzlr** [comment]
I'll have a look at the tests. I've not recognized them before because I'm used to *pytest* which has an extra folder `./tests` instead of the unittest module with a `test.py` file inside the package structure. Anyway, I'll test and extend them if necessary.

**Edit**: Done ✔️

**Comment by adtzlr** [comment]
Just as a side note: Personally, I'm a big fan of using a code formatter like [black](https://github.com/psf/black). I won't apply black here because it would change every file but I'd suggest to have a look at it. It makes collaborating much easier because everyone has some personal preferences on code formatting - and black unifies it. Not always best, but at least consistent.

**Comment by Gunnstein** [comment]
Dear @adtzlr,

Thank you for your contribution, I especially appreciate the tests! I will also have a look at Black and consider it for future versions of fatpack and for my other projects. 

First of all, I agree that it would be useful to have a function return both closed and open rainflow cycles, i.e. also include open cycles inherent in the residue. This is not only useful in the case of establishing start-destination rainflow matrices, but also elsewhere, e.g. in extracting the rainflow ranges.

However, I do not think `find_rainflow_ranges` is the correct function to implement it in, simply because this function finds and returns the rainflow ranges. Instead, I think it is more appropriate to include it as an option in the function `find_rainflow_cycles`, this function finds and returns cycles. The signature would then be something like `find_rainflow_cycles(reversals, include_open_cycles=False)`. Do you have any thoughts on this ? 

When it comes to your suggestion of "flipping" the columns the cycles I think this implements inconsistent/incorrect results. Your example does not contain any closed cycles according to the 4-point rainflow cycle counting algorithm defined in ISO 12110-2 which fatpack implements. Upon concatenation of the residual to obtain open cycles by a second pass, you obtain a new signal, which in fact contains one cycle from -1 to 1.

Best regards,
Gunnstein

**Comment by adtzlr** [comment]
Hey @Gunnstein, thank you for your response and your suggestions!

`find_rainflow_cycles(reversals, include_open_cycles=False)` sounds like a natural choice 👍🏻 of implementing such a feature.

Actually, I was and I am still unsure about the correctness of my proposed implementation of counting the remaining open-cycles as by flipping the columns in the second pass for the *from-to* array. Good argumentation, I'll have a look at it in the next days.

Best regards,
Andreas

**Comment by adtzlr** [comment]
If I understand your suggestion right @Gunnstein, this requires the following change:

Move the (duplicated) code-blocks for the first- and second-pass from `find_rainflow_ranges()` and `find_rainflow_ranges_strict()` to `find_rainflow_cycles(include_open_cycles=False)`.

I think it will be better to implement this in a different branch. I'll open a new pull-request and close this to avoid further confusions.

**Pull request closed without merging**
